JOB_STATUS_PENDING = "pending"
JOB_STATUS_PROCESSING = "processing"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"

JOB_KIND_INDIVIDUAL = "individual"
JOB_KIND_INTEGRATED = "integrated"

ACTIVE_JOB_STATUSES = (JOB_STATUS_PENDING, JOB_STATUS_PROCESSING)
FINAL_JOB_STATUSES = (JOB_STATUS_COMPLETED, JOB_STATUS_FAILED)
